import { useEffect } from 'react';
import { ArrowUpRight, Instagram, Mail, MessageCircle, Youtube } from 'lucide-react';
import { SITE, YOUTUBE_CHANNELS, SOCIALS, BRAND_CAMPAIGNS } from './data/core';

const profileImage = 'https://raw.githubusercontent.com/ultraop-in/ultra-in.github.io/main/images/ahsan-profile.png';
const youtube = YOUTUBE_CHANNELS[0];

const faqs = [
  ['Who is Sk Ahsan Ahmad?', 'Sk Ahsan Ahmad is the creator behind UltraOP, a creator identity built around gaming, live streaming, storytelling, community and technology. UltraOP brings the creator\'s official channels, social platforms, collaborations and projects into one connected network.'],
  ['What is UltraOP?', 'UltraOP is the official creator network and public identity of Sk Ahsan Ahmad. It covers gaming content, live streams, Minecraft, Roblox, community projects, brand collaborations and technology-focused creator work.'],
  ['What does UltraOP create?', 'UltraOP creates gaming videos, live streams, short-form content, creator stories, Minecraft content, Roblox content, community experiences, brand campaigns and technology projects.'],
  ['What games does UltraOP focus on?', 'Minecraft is a major current focus, alongside Roblox and other gaming content. Ultra OP Live also covers live streams and other games as the network evolves.'],
  ['What is the main UltraOP YouTube channel?', `Ultra OP Live is the main live and gaming destination. It focuses on live streams, Minecraft and other games. The official channel is ${youtube.handle}.`],
  ['How many official YouTube channels does UltraOP have?', 'UltraOP currently operates four official YouTube channels: Ultra OP Live, Roblox UltraOP3, Ultra OP 2.0 (Minecraft), and Op Earnings. Each channel has a distinct role inside the network.'],
  ['Where can I watch UltraOP?', 'The official creator network is available across YouTube, Instagram, Twitch, Kick, Rooter, Discord and WhatsApp. The website keeps the verified destinations together so visitors can always start from an official link.'],
  ['Where can I follow Sk Ahsan Ahmad on Instagram?', 'The main official Instagram profile is @ultraopp. Additional official profiles include @op_earnings and @ahsannow for specific creator and earnings content.'],
  ['Does UltraOP do brand collaborations?', 'Yes. UltraOP works on creator-native campaigns and partnerships across gaming, technology, lifestyle and youth culture. Past campaign work includes Amazon, THE FINALS, Wild Stone, Hero, Parallel Mobile and TVS.'],
  ['How can a brand work with UltraOP?', `Professional enquiries can be sent to ${SITE.businessEmail}. Campaigns, sponsorships, creator integrations and media enquiries can be discussed directly through the business contact page.`],
  ['Is UltraOP a gaming company?', 'No. UltraOP is a creator network and personal creator brand. Gaming is a major part of the content, but the broader identity also includes storytelling, community, media, technology and creator projects.'],
  ['What is the story behind UltraOP?', 'The creator journey began with competitive gaming and organised communities, moved through scrims and live-streaming work, continued through years of community activity on Rooter, and then expanded through YouTube into a broader creator network.'],
  ['What is the current Minecraft identity?', 'The current Minecraft identity is Ultra_OP_Live. The website uses that Minecraft account identity for the creator asset library and current character presentation.'],
  ['Does UltraOP build technology projects?', 'Yes. Technology and creator tooling are part of the wider UltraOP direction, including websites, media workflows, Minecraft-related projects, recording tools and other creator-focused builds.'],
  ['Can I contact UltraOP for media enquiries?', `Yes. Media enquiries, sponsorships, collaborations and professional opportunities can be sent to ${SITE.businessEmail}.`],
  ['Where can I find official UltraOP assets?', 'The Assets page is the creator media library for approved logos, wallpapers, stream-kit resources, brand materials, video assets, Minecraft identity resources and creator photography.'],
  ['Can I use UltraOP logos or creator photos?', 'Only use assets according to the permission or usage information supplied with each asset. The public asset library is intended to keep approved creator resources organised rather than implying unrestricted commercial usage.'],
  ['How can I join the UltraOP community?', 'The official Discord and social destinations are the best starting points for community participation. The Community page keeps those verified links together.'],
  ['Is this the official UltraOP website?', 'Yes. ultraop.in is the official UltraOP creator website and is intended to be the central reference point for the creator, channels, community, brand work, journal and approved assets.'],
  ['How can I stay updated with new UltraOP projects?', 'Follow the official YouTube and social channels linked throughout the website. The Journal and creator pages also document the larger story behind the network and its projects.'],
];

function MetaAndSchema() {
  useEffect(() => {
    document.title = 'About Sk Ahsan Ahmad — UltraOP | Gaming Creator, Streamer & Builder';
    const description = 'Learn about Sk Ahsan Ahmad, the creator behind UltraOP: gaming creator, streamer, Minecraft and Roblox creator, storyteller, community builder and technology-focused creator.';
    const setMeta = (name: string, content: string) => {
      let node = document.querySelector<HTMLMetaElement>(`meta[name="${name}"]`);
      if (!node) { node = document.createElement('meta'); node.name = name; document.head.appendChild(node); }
      node.content = content;
    };
    setMeta('description', description);
    setMeta('keywords', 'Sk Ahsan Ahmad, UltraOP, Ultra OP, UltraOP creator, gaming creator India, gaming streamer India, Minecraft creator India, Roblox creator, YouTube creator, live streamer, content creator, creator network');
    setMeta('author', 'Sk Ahsan Ahmad / UltraOP');
    let canonical = document.querySelector<HTMLLinkElement>('link[rel="canonical"]');
    if (!canonical) { canonical = document.createElement('link'); canonical.rel = 'canonical'; document.head.appendChild(canonical); }
    canonical.href = 'https://ultraop.in/about/';
    return () => { document.title = 'UltraOP — Official Creator Website'; };
  }, []);
  const schema = { '@context': 'https://schema.org', '@type': 'Person', name: 'Sk Ahsan Ahmad', alternateName: ['UltraOP', 'Ultra OP'], url: 'https://ultraop.in/about/', image: 'https://ultraop.in/brand-assets/profile.png', jobTitle: 'Gaming Creator, Streamer & Builder', description: 'Sk Ahsan Ahmad is the creator behind UltraOP, a creator network spanning gaming, live streaming, Minecraft, Roblox, community, brand work and technology.', email: SITE.businessEmail, sameAs: [SITE.youtube, SITE.instagram, SITE.discord, ...SOCIALS.map(item => item.url)] };
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}/><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}/></>;
}

export default function AboutPagePro() {
  return <div className="creator-page about-pro-page">
    <MetaAndSchema/>
    <header className="creator-page-header"><div className="creator-page-header-inner"><a className="creator-page-brand" href="/"><img src="/brand/ultraop-mark.svg" alt="UltraOP"/><span>ULTRA<span>OP</span></span></a><nav>{[['/', 'Home'], ['/about/', 'About'], ['/channels/', 'Channels'], ['/live/', 'Live'], ['/community/', 'Community'], ['/work/', 'Brand Work']].map(([href, label]) => <a key={href} href={href}>{label}</a>)}</nav><a className="creator-menu-button about-menu-link" href="/contact/" aria-label="Contact UltraOP"><Mail size={19}/></a></div></header>
    <main>
      <section className="creator-page-hero about-pro-hero"><div className="creator-page-hero-copy"><p className="creator-eyebrow">ABOUT / SK AHSAN AHMAD / ULTRAOP</p><h1>The creator behind<br/><em>UltraOP.</em></h1><p>Sk Ahsan Ahmad is the creator behind UltraOP — a gaming, live-streaming, storytelling, community and technology network built in public over years of content, experiments and creator work.</p></div><div className="creator-page-hero-index">01<br/><span>CREATOR PROFILE / OFFICIAL</span></div></section>
      <section className="about-pro-intro"><div className="about-pro-photo"><img src={profileImage} onError={e => { e.currentTarget.src = '/creator/creator-photo.svg'; }} alt="Sk Ahsan Ahmad, creator behind UltraOP"/><span>SK AHSAN AHMAD / ULTRAOP</span></div><div className="about-pro-copy"><p className="creator-kicker">WHO IS ULTRAOP?</p><h2>More than a channel. A connected creator identity.</h2><p>UltraOP is the public creator identity of Sk Ahsan Ahmad. What started around competitive gaming and live streaming gradually became a larger ecosystem: official YouTube channels, gaming communities, social platforms, brand collaborations, creator media and technology projects.</p><p>The purpose of this network is to keep everything connected without making every platform feel the same. Minecraft can have its own identity. Roblox can have its own audience. Live streams can stay immediate. Brand work can remain professional. The creator story can still tie all of it together.</p><div className="about-pro-facts"><div><b>04</b><span>Official YouTube channels</span></div><div><b>600K+</b><span>Combined audience snapshot</span></div><div><b>01</b><span>Connected creator network</span></div></div></div></section>
      <section className="about-pro-story"><div><p className="creator-kicker">THE JOURNEY</p><h2>From competitive gaming to a creator network.</h2></div><div className="about-pro-story-copy"><p>The early chapter was rooted in competitive gaming. PUBG, organised teams, scrims and gaming communities shaped the first part of the journey. Those experiences taught the fundamentals that still matter today: consistency, teamwork, audience connection and the ability to turn a game into a story.</p><p>The next chapter moved into live streaming and community work, including years of activity around Rooter. Streaming changed the relationship with the audience. Instead of simply publishing a finished video, the creator could build a community around shared moments, conversations and long sessions.</p><p>YouTube then became the next major platform. The network expanded from gaming uploads into multiple focused channels, allowing different interests to grow without losing the common UltraOP identity.</p><p>Today, Minecraft is a major creative focus, with Roblox and other gaming formats also part of the wider direction. Alongside content, UltraOP continues to explore technology, creator tooling, websites, recording workflows and original projects.</p></div></section>
      <section className="about-pro-network"><div className="about-pro-network-head"><p className="creator-kicker">THE NETWORK</p><h2>Four official YouTube destinations.</h2><p>Each channel has a clear purpose while remaining part of the same UltraOP ecosystem.</p></div><div className="about-pro-channel-list">{YOUTUBE_CHANNELS.map((channel, i) => <a href={channel.url} target="_blank" rel="noreferrer" key={channel.id}><span>0{i + 1}</span><div><strong>{channel.name}</strong><small>{channel.focus}</small></div><ArrowUpRight size={16}/></a>)}</div></section>
      <section className="about-pro-work"><div><p className="creator-kicker">BRAND & CREATOR WORK</p><h2>Professional work built around the audience.</h2></div><div><p>UltraOP approaches brand partnerships as creator work rather than generic placements. Campaigns can sit naturally inside gaming, technology, lifestyle and youth culture while keeping the creator voice intact.</p><div className="about-pro-brand-list">{BRAND_CAMPAIGNS.map(brand => <span key={brand.name}>{brand.name}</span>)}</div><a className="about-pro-link" href="/work/">Explore brand work <ArrowUpRight size={15}/></a></div></section>
      <section className="about-pro-community"><div><p className="creator-kicker">COMMUNITY</p><h2>Stay connected to the official network.</h2></div><div><p>The community exists across YouTube, Instagram, Discord, Twitch, Kick, Rooter and WhatsApp. The goal is to give people a reliable official starting point regardless of where they prefer to follow creators.</p><div className="about-pro-socials"><a href={SITE.youtube} target="_blank" rel="noreferrer"><Youtube size={16}/> YouTube</a><a href={SITE.instagram} target="_blank" rel="noreferrer"><Instagram size={16}/> Instagram</a><a href={SITE.discord} target="_blank" rel="noreferrer"><MessageCircle size={16}/> Discord</a></div></div></section>
      <section className="about-pro-faq"><div className="about-pro-faq-head"><p className="creator-kicker">FAQ / SEARCHABLE KNOWLEDGE</p><h2>Frequently asked questions about UltraOP.</h2><p>Clear answers about the creator, channels, gaming focus, collaborations, community and official website.</p></div><div className="about-pro-faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
      <section className="about-pro-contact"><div><p className="creator-kicker">BUSINESS / MEDIA / COLLABORATIONS</p><h2>Have a professional enquiry?</h2><p>For sponsorships, campaigns, creator collaborations, media enquiries and professional opportunities.</p></div><a href={`mailto:${SITE.businessEmail}`}>{SITE.businessEmail}<ArrowUpRight size={16}/></a></section>
    </main>
    <footer className="creator-page-footer"><div className="creator-footer-top"><div><a className="creator-page-brand" href="/"><img src="/brand/ultraop-mark.svg" alt="UltraOP"/><span>ULTRA<span>OP</span></span></a><p>Gaming, storytelling, community and technology — built around the UltraOP creator network.</p></div><div className="creator-footer-links"><a href="/channels/">Channels <ArrowUpRight size={13}/></a><a href="/work/">Brand Work <ArrowUpRight size={13}/></a><a href="/journal/">Journal <ArrowUpRight size={13}/></a><a href="/assets/">Assets <ArrowUpRight size={13}/></a><a href="/contact/">Contact <ArrowUpRight size={13}/></a></div><div className="creator-footer-contact"><span>BUSINESS</span><a href={`mailto:${SITE.businessEmail}`}>{SITE.businessEmail}</a><a href={SITE.youtube} target="_blank" rel="noreferrer">YouTube <ArrowUpRight size={13}/></a></div></div><div className="creator-footer-bottom"><span>© {new Date().getFullYear()} UltraOP / Sk Ahsan Ahmad</span><span><a href="/terms.html">Terms</a><a href="/privacy.html">Privacy</a></span></div></footer>
  </div>;
}
