import { useState, type ReactNode } from 'react';
import { ArrowLeft, ArrowUpRight, ChevronDown, Instagram, Mail, Menu, MessageCircle, X, Youtube } from 'lucide-react';
import { SITE, YOUTUBE_CHANNELS, SOCIALS, BRAND_CAMPAIGNS } from './data/core';
import { JOURNAL_ENTRIES } from './data/journal';

const profileImage = 'https://raw.githubusercontent.com/ultraop-in/ultra-in.github.io/main/images/ahsan-profile.png';

const pageLinks = [
  ['/', 'Home'], ['/about/', 'About'], ['/channels/', 'Channels'], ['/live/', 'Live'], ['/community/', 'Community'], ['/work/', 'Brand Work'], ['/fan-art/', 'Fan Art'], ['/assets/', 'Assets'], ['/journal/', 'Journal'], ['/contact/', 'Contact'],
];

function Brand() { return <a className="creator-page-brand" href="/"><img src="/brand/ultraop-mark.svg" alt="UltraOP"/><span>ULTRA<span>OP</span></span></a>; }
function PageHeader() { const [open, setOpen] = useState(false); return <header className="creator-page-header"><div className="creator-page-header-inner"><Brand/><nav>{pageLinks.slice(0, 6).map(([href, label]) => <a key={href} href={href}>{label}</a>)}</nav><button className="creator-menu-button" onClick={() => setOpen(v => !v)} aria-label="Open navigation">{open ? <X size={21}/> : <Menu size={21}/>}</button></div>{open && <div className="creator-mobile-menu">{pageLinks.map(([href, label]) => <a key={href} href={href} onClick={() => setOpen(false)}>{label}<ArrowUpRight size={15}/></a>)}</div>}</header>; }
function Footer() { return <footer className="creator-page-footer"><div className="creator-footer-top"><div><Brand/><p>Gaming, storytelling, community and technology — built around the UltraOP creator network.</p></div><div className="creator-footer-links">{pageLinks.slice(1).map(([href, label]) => <a key={href} href={href}>{label}<ArrowUpRight size={13}/></a>)}</div><div className="creator-footer-contact"><span>BUSINESS</span><a href={`mailto:${SITE.businessEmail}`}>{SITE.businessEmail}</a><a href={SITE.youtube} target="_blank" rel="noreferrer">YouTube <ArrowUpRight size={13}/></a></div></div><div className="creator-footer-bottom"><span>© {new Date().getFullYear()} UltraOP / Sk Ahsan Ahmad</span><span><a href="/terms.html">Terms</a><a href="/privacy.html">Privacy</a></span></div></footer>; }
function Layout({ eyebrow, title, intro, children }: { eyebrow: string; title: ReactNode; intro?: string; children: ReactNode }) { return <div className="creator-page"><PageHeader/><main><section className="creator-page-hero"><div className="creator-page-hero-copy"><p className="creator-eyebrow">{eyebrow}</p><h1>{title}</h1>{intro && <p>{intro}</p>}</div><div className="creator-page-hero-index">ULTRAOP<br/><span>OFFICIAL CREATOR NETWORK</span></div></section>{children}</main><Footer/></div>; }

export function AboutPage() { return <Layout eyebrow="ABOUT / THE CREATOR" title={<>A creator built<br/><em>in public.</em></>} intro="UltraOP is the creator identity of Sk Ahsan Ahmad — connecting gaming, live streaming, storytelling, community and technology under one network."><section className="creator-two-col"><div className="creator-photo-card"><img src={profileImage} onError={e => { e.currentTarget.src = '/creator/creator-photo.svg'; }} alt="Sk Ahsan Ahmad"/><span>SK AHSAN AHMAD / 001</span></div><div><p className="creator-kicker">THE SHORT VERSION</p><h2>Player → streamer → creator & builder.</h2><p>The journey began with PUBG in India, moved through competitive communities and organised scrims, then into years of live streaming and community work on Rooter. YouTube became the next chapter — first with Free Fire, then broader gaming content and a growing creator network.</p><p>Today the focus is Minecraft, gaming storytelling, future Roblox projects and technology builds. The goal is simple: make the creator ecosystem feel like one connected world instead of a collection of disconnected profiles.</p><div className="creator-facts"><div><b>04</b><span>Official YouTube channels</span></div><div><b>08</b><span>Verified destinations</span></div><div><b>01</b><span>Creator universe</span></div></div></div></section></Layout>; }
function ChannelTile({ channel, index }: { channel: typeof YOUTUBE_CHANNELS[number]; index: number }) { return <article className="creator-channel-tile"><div className="creator-channel-media"><iframe title={channel.name} src={`https://www.youtube.com/embed/videoseries?list=${channel.uploadsPlaylist}&rel=0&modestbranding=1`} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/><span>0{index + 1}</span></div><div className="creator-channel-info"><p>{channel.handle}</p><h2>{channel.name}</h2><span>{channel.focus}</span><a href={`${channel.url}?sub_confirmation=1`} target="_blank" rel="noreferrer">Subscribe <ArrowUpRight size={14}/></a></div></article>; }
export function ChannelsPage() { return <Layout eyebrow="CHANNELS / THE NETWORK" title={<>Four channels.<br/><em>One identity.</em></>} intro="The official UltraOP YouTube network, built to make room for future channels without changing the architecture."><section className="creator-channel-grid">{YOUTUBE_CHANNELS.map((channel, i) => <ChannelTile key={channel.id} channel={channel} index={i}/>)}</section></Layout>; }
export function LivePage() { const twitch = SOCIALS.find(s => s.name === 'Twitch'); const kick = SOCIALS.find(s => s.name === 'Kick'); const rooter = SOCIALS.find(s => s.name === 'Rooter'); return <Layout eyebrow="LIVE / STREAMING" title={<>When the stream<br/><em>starts, be there.</em></>} intro="Follow the official streaming destinations. Live availability is controlled by each platform."><section className="creator-live-feature"><div className="creator-live-screen"><iframe title="Ultra OP Live" src={`https://www.youtube.com/embed/videoseries?list=${YOUTUBE_CHANNELS[0].uploadsPlaylist}&rel=0&modestbranding=1`} allowFullScreen/></div><div className="creator-live-copy"><span className="creator-live-dot">● LIVE PRESENCE</span><h2>Gaming, live and unfiltered.</h2><p>Ultra OP Live is the main live destination for Minecraft and other games. The channel network keeps live content close to the rest of the creator ecosystem.</p><div className="creator-live-buttons"><a className="youtube" href={YOUTUBE_CHANNELS[0].url} target="_blank" rel="noreferrer"><Youtube size={16}/> YouTube <ArrowUpRight size={13}/></a>{twitch && <a className="twitch" href={twitch.url} target="_blank" rel="noreferrer">Twitch <ArrowUpRight size={13}/></a>}{kick && <a className="kick" href={kick.url} target="_blank" rel="noreferrer">Kick <ArrowUpRight size={13}/></a>}{rooter && <a className="rooter" href={rooter.url} target="_blank" rel="noreferrer">Rooter <ArrowUpRight size={13}/></a>}</div></div></section></Layout>; }
export function CommunityPage() { return <Layout eyebrow="COMMUNITY / THE NETWORK" title={<>Stay close.<br/><em>Everywhere.</em></>} intro="The community lives across social, streaming and messaging platforms — each with a different role in the UltraOP ecosystem."><section className="creator-social-grid">{SOCIALS.map(s => <a className="creator-social-tile" href={s.url} target="_blank" rel="noreferrer" key={s.url}><span>{s.type}</span><h2>{s.name}</h2><p>{s.handle}</p><ArrowUpRight size={18}/></a>)}</section><section className="creator-community-note"><div><p className="creator-kicker">DIRECT SUPPORT</p><h2>Build the next chapter with UltraOP.</h2></div><div><p>For community, collaborations and creator conversations, use the official destinations above. For professional enquiries, contact the business address directly.</p><a href={`mailto:${SITE.businessEmail}`}>Business enquiries <ArrowUpRight size={14}/></a></div></section></Layout>; }
export function WorkPage() { return <Layout eyebrow="BRAND WORK / COLLABORATIONS" title={<>Creator work<br/><em>with purpose.</em></>} intro="A focused space for campaigns, creator integrations and brand partnerships across gaming, technology, lifestyle and youth culture."><section className="creator-work-grid">{BRAND_CAMPAIGNS.map((brand, i) => <article key={brand.name} className="creator-work-card"><div><span>0{i + 1}</span><strong>{brand.name}</strong></div><p>{brand.type}</p><small>{brand.category} · {brand.year}</small></article>)}</section><section className="creator-work-cta"><p className="creator-kicker">BUSINESS / PARTNERSHIPS</p><h2>Have a campaign worth building?</h2><a href={`mailto:${SITE.businessEmail}`}>Start a conversation <ArrowUpRight size={15}/></a></section></Layout>; }
export function ContactPage() { return <Layout eyebrow="CONTACT / BUSINESS" title={<>Let's build<br/><em>something real.</em></>} intro="For sponsorships, campaigns, creator collaborations, media enquiries and professional opportunities."><section className="creator-contact-grid"><a className="creator-contact-card primary" href={`mailto:${SITE.businessEmail}`}><Mail size={22}/><span>BUSINESS EMAIL</span><h2>{SITE.businessEmail}</h2><ArrowUpRight size={18}/></a><a className="creator-contact-card" href={SITE.youtube} target="_blank" rel="noreferrer"><Youtube size={22}/><span>YOUTUBE</span><h2>@ultraoplive</h2><ArrowUpRight size={18}/></a><a className="creator-contact-card" href={SITE.instagram} target="_blank" rel="noreferrer"><Instagram size={22}/><span>INSTAGRAM</span><h2>@ultraopp</h2><ArrowUpRight size={18}/></a><a className="creator-contact-card" href={SITE.discord} target="_blank" rel="noreferrer"><MessageCircle size={22}/><span>DISCORD</span><h2>UltraOP Community</h2><ArrowUpRight size={18}/></a></section></Layout>; }
export function JournalLandingPage() { return <Layout eyebrow="JOURNAL / THE STORY" title={<>The story behind<br/><em>the uploads.</em></>} intro="The long-form creator history belongs here — from PUBG and esports to Rooter, YouTube, Minecraft and the next UltraOP era."><section className="creator-journal-list">{JOURNAL_ENTRIES.map((entry, i) => <a href={`/journal/#${entry.slug}`} key={entry.slug}><span>0{String(i + 1).padStart(1, '0')}</span><div><small>{entry.era}</small><h2>{entry.title}</h2><p>{entry.summary}</p></div><ArrowUpRight size={18}/></a>)}</section></Layout>; }
export function Creator404() { return <Layout eyebrow="404 / NOT FOUND" title={<>Wrong<br/><em>turn.</em></>} intro="That UltraOP page does not exist."><div className="creator-404"><a href="/"><ArrowLeft size={15}/> Back home</a></div></Layout>; }
