import { ArrowUpRight, Menu, X, Image as ImageIcon, PackageOpen, Gamepad2 } from 'lucide-react';
import { useState, type ReactNode } from 'react';

const links = [
  ['/', 'Home'], ['/about/', 'About'], ['/channels/', 'Channels'], ['/live/', 'Live'], ['/community/', 'Community'], ['/work/', 'Brand Work'], ['/journal/', 'Journal'], ['/fan-art/', 'Fan Art'], ['/assets/', 'Assets'], ['/contact/', 'Contact'],
];

function Brand(){return <a className="creator-page-brand" href="/"><img src="/brand/ultraop-mark.svg" alt="UltraOP"/><span>ULTRA<span>OP</span></span></a>}
function Header(){const [open,setOpen]=useState(false);return <header className="creator-page-header"><div className="creator-page-header-inner"><Brand/><nav>{links.map(([href,label])=><a key={href} href={href}>{label}</a>)}</nav><button className="creator-menu-button" onClick={()=>setOpen(v=>!v)} aria-label="Open navigation">{open?<X size={21}/>:<Menu size={21}/>}</button></div>{open&&<div className="creator-mobile-menu">{links.map(([href,label])=><a key={href} href={href} onClick={()=>setOpen(false)}>{label}<ArrowUpRight size={15}/></a>)}</div>}</header>}
function Footer(){return <footer className="creator-page-footer"><div className="creator-footer-top"><div><Brand/><p>Fan art, official creator assets and the UltraOP gaming world — kept in one organised library.</p></div><div className="creator-footer-links">{links.slice(1).map(([href,label])=><a key={href} href={href}>{label}<ArrowUpRight size={13}/></a>)}</div><div className="creator-footer-contact"><span>CREATOR LIBRARY</span><a href="/fan-art/">Fan Art <ArrowUpRight size={13}/></a><a href="/assets/">Assets <ArrowUpRight size={13}/></a></div></div><div className="creator-footer-bottom"><span>© {new Date().getFullYear()} UltraOP / Sk Ahsan Ahmad</span><span><a href="/terms.html">Terms</a><a href="/privacy.html">Privacy</a></span></div></footer>}
function Layout({eyebrow,title,intro,children}:{eyebrow:string;title:ReactNode;intro:string;children:ReactNode}){return <div className="creator-page"><Header/><main><section className="creator-page-hero"><div className="creator-page-hero-copy"><p className="creator-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p></div><div className="creator-page-hero-index">ULTRAOP<br/><span>CREATOR LIBRARY</span></div></section>{children}</main><Footer/></div>}

export function FanArtPage(){return <Layout eyebrow="FAN ART / COMMUNITY" title={<>Made by fans.<br/><em>Shown with love.</em></>} intro="A dedicated gallery for community-made UltraOP fan art. Approved artwork can be added here without touching the rest of the site."><section className="gallery-page-section"><div className="gallery-section-head"><div><p className="creator-kicker">FAN ART LIBRARY</p><h2>Community creations</h2></div><span>READY FOR UPLOADS</span></div><div className="gallery-placeholder-grid"><article><ImageIcon size={28}/><strong>Fan Art 01</strong><p>Drop the first approved artwork into <code>/public/gallery/fan-art/</code>.</p></article><article><ImageIcon size={28}/><strong>Fan Art 02</strong><p>More community artwork can be added without changing the layout.</p></article><article><ImageIcon size={28}/><strong>Fan Art 03</strong><p>Use WEBP, JPG, JPEG or PNG for the best web performance.</p></article></div></section></Layout>}

export function AssetsPage(){const skin=`https://mc-heads.net/body/Ultra_OP_Live/500.png?v=${Math.floor(Date.now()/3600000)}`;return <Layout eyebrow="ASSETS / CREATOR KIT" title={<>The UltraOP<br/><em>asset shelf.</em></>} intro="Official creator media, wallpapers, overlays, graphics and gaming resources can live here as a clean, downloadable library."><section className="gallery-page-section"><div className="gallery-section-head"><div><p className="creator-kicker">MINECRAFT IDENTITY</p><h2>Ultra_OP_Live</h2></div><span>AUTOMATIC SKIN SOURCE</span></div><div className="minecraft-identity-card"><div className="minecraft-skin"><img src={skin} alt="Minecraft character skin for Ultra_OP_Live" loading="eager"/><div><b>Ultra_OP_Live</b><span>Minecraft username</span></div></div><div className="minecraft-skin-copy"><Gamepad2 size={24}/><h3>Current Minecraft skin</h3><p>The character render is resolved from the Minecraft username <strong>Ultra_OP_Live</strong>. When the account skin changes, the gallery source follows the current skin automatically.</p><small>Source: MC Heads · refreshed hourly</small></div></div></section><section className="gallery-page-section"><div className="gallery-section-head"><div><p className="creator-kicker">DOWNLOAD LIBRARY</p><h2>Creator assets</h2></div><span>READY FOR UPLOADS</span></div><div className="gallery-asset-grid"><article><PackageOpen size={28}/><strong>Wallpapers</strong><p>Desktop and mobile UltraOP wallpapers.</p></article><article><PackageOpen size={28}/><strong>Stream Kit</strong><p>Overlays, panels and creator graphics.</p></article><article><PackageOpen size={28}/><strong>Brand Kit</strong><p>Official logos and approved identity assets.</p></article><article><PackageOpen size={28}/><strong>Video Assets</strong><p>Thumbnails, end cards and reusable media.</p></article></div><p className="gallery-storage-note">Upload approved files to <code>/public/gallery/assets/</code> to keep the library organised.</p></section></Layout>}
